### ISSUE TITLE
hCaptcha verification on server join

### ISSUE THREAD

**Issue by Di3gorios** [BitStore-Community/BitBoost#5]
i put in working tokens and it closes program

**Comment by DaniEnsi** [comment]
There is an issue with the captcha verification of tokens, right now... Please make sure to only use fully verified tokens with it, until i fix it...

**Comment by wkg** [comment]
I'm getting Errors 401 or 400 when attempting to join a server, currently investigating

**Comment by jayjaychukwu** [comment]
> There is an issue with the captcha verification of tokens, right now... Please make sure to only use fully verified tokens with it, until i fix it...

Was there ever a captcha bypassing feature?

**Comment by DaniEnsi** [comment]
> > There is an issue with the captcha verification of tokens, right now... Please make sure to only use fully verified tokens with it, until i fix it...
> 
> Was there ever a captcha bypassing feature?

There was one, on a different version i made, but i used chaptacloud. I did want to offer a actually free product so i left it out, which worked for quite a while until discord added more captchas...

**Comment by JonasPeitz** [comment]
> > > There is an issue with the captcha verification of tokens, right now... Please make sure to only use fully verified tokens with it, until i fix it...
> > 
> > 
> > Was there ever a captcha bypassing feature?
> 
> There was one, on a different version i made, but i used chaptacloud. I did want to offer a actually free product so i left it out, which worked for quite a while until discord added more captchas...

hey, dansi was ist eigentlici deine Discord ID?

**Comment by DaniEnsi** [comment]
1006086677007183922
